### PR TITLE
Create remix_tshirt_back.svg

### PR DESCRIPTION
**Pull request by mgiraldo**

### CODE REVIEW

**Comment by ablwr** [comment]
🔵 🔷 💙  🔵 🔷 💙  🔵 🔷 💙 👾

**Comment by ablwr** [comment]
Shocked these commits don't begin with a 👾, it's like I don't even know you anymore @mgiraldo !

**Comment by mgiraldo** [comment]
😔

**Comment by ablwr** [comment]
😊

**Pull request merged**
